### ISSUE TITLE
USER STORY: Site purpose

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#1]
As a **visiting user** I can **easily find out what the purpose of the website is and learn more about the site owner and the products being sold** so that **I can decide to stay and browse or not**

# Acceptance Criteria
 *  Acceptance Criteria 1:  The first thing the user should see on entering the website is an image which sets the tone of the website and a tagline explaining the purpose of the website
 *  Acceptance Criteria 2: There should be a learn more button, which will link to the information about the maker and the website
 *  Acceptance Criteria 3: There should be a 'Shop now' button which will link to the shop, the primary purpose of the website
 * Acceptance Criteria 4: Below the main image, there should be a section explaining to users what the website is for, and introducing the website owner who makes the products

# Tasks
 - [x] update index.html in home app with the images and content
 - [x] add CSS
 - [x] Test manually to ensure links
 - [x] Re-run automated test for home page

**Comment by Fiona-T** [comment]
Tasks completed and acceptance criteria met. Learn more button linked up, Shop button and other links to be added once the pages are created. Tested Learn more button link manually. Re-ran automated test on home page. Closed.
