### ISSUE TITLE
USER STORY: Sort products in shop

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#10]
As a **site user** I can **sort the products in the shop** so that **I can find what I'm looking for more easily**

# Acceptance Criteria
 *  Acceptance Criteria 1: there is an option in the shop page menu bar to sort products
 *  Acceptance Criteria 2: the user can choose one of these options, and the products are sorted according to the choice 
 *  Acceptance Criteria 3: the choices should be: by product name (A to Z), by product name (Z to A), by price (low to high), by price (high to low) 

# Tasks
 - [x] Add a sub header to the shop pages, where the sorting option dropdown will be shown
 - [x] Add any CSS as needed
 - [x] Update the show_products view to check if sorting was requested, and to return the products sorted if there was 
 - [x] Create script to update the url based on the selected option - so that get request passed to view
 - [x] Test the functionality

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual and automated testing completed. Closed.
