### ISSUE TITLE
USER STORY: Search for a product in the shop

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#11]
As a **site user** I can **search for a product in the shop** so that **I can find a particular item quickly**

# Acceptance Criteria
 *  Acceptance Criteria 1: There is a search box at the top of the shop page
 *  Acceptance Criteria 2: The user can enter a search term and the page will display products that match that search term
 *  Acceptance Criteria 3: The search should return if the word is in the product name, or product description

# Tasks
 - [x] Create header/menu bar for Shop page, that will hold the search box (as well as category options - see #9 )
 - [x]  Add the search form to the menu
 - [x] Style the menu and make sure it is responsive (will contain category headings and search bar so will collapse to hamburger at smaller screen size)
 - [x] Update the show_products view to check the search terms and return products that match the search terms
 - [x] Test the functionality

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual and automated tests completed. Closed.
