### ISSUE TITLE
USER STORY: Add item to cart

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#12]
As a **site user** I can **add an item to my cart** so that **I can buy it**

# Acceptance Criteria
 *  Acceptance Criteria 1:  from the product details page, a user can click on the Add to Bag button, to add an item to their bag
 *  Acceptance Criteria 2:  the subtotal underneath the Bag icon in the header should update to show the new total in the bag

# Tasks
 - [x] Create bag app, add to installed apps and project urls
 - [x] create bag.html template, url and basic view
 - [x] create contexts.py to store the bag items context so it is accessible to entire site, add to settings.py
 - [x] create view to add to bag (and create url)
 - [x] update the form in product_details.html to use this view
 - [x] test the functionality - manual testing needs to be done in conjunction with #15

**Comment by Fiona-T** [comment]
Tasks completed and acceptance criteria met. Manual and automated tests done. Closed.
