### ISSUE TITLE
USER STORY: See items in cart

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#15]
As a **site user** I can **see the items in my cart at any time** so that **I can check what I have already added to the cart**

# Acceptance Criteria
 *  Acceptance Criteria 1: a user can click on the Bag icon from the header and this brings them to a page showing the items that they have added to the bag
 *  Acceptance Criteria 2: there is a message if no items have been added, with button to return to shop
 *  Acceptance Criteria 3: the details shown for each item in the cart are: product details (image + product name), price, quantity and subtotal
 * Acceptance Criteria 4: underneath the listed items is a total, delivery charge amount and subtotal

# Tasks
 - [x] update cart.html (should be created in #12 ) to show the required details
 - [x] view should be created in #12 when bag app was created - amend view if necessary
 - [x] add CSS as required
 - [x] add logic to show message if no items in cart
 - [x] add delivery threshold to settings.py and contexts.py so delivery can be calculated
 - [x] update the Cart link in header to link to cart.html page
 - [x] test the functionality

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual and automated testing done. Closed.
