### ISSUE TITLE
USER STORY: Remove item from cart

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#17]
As a **site user** I can **remove an item from my cart** so that **I do not have to buy it if I've changed my mind**

# Acceptance Criteria
 *  Acceptance Criteria 1:  when a user is on the bag page, there is a button/link beside each item in the cart to remove that item
 *  Acceptance Criteria 2: once they click the button/link, the item is removed and the totals update accordingly
 *  Acceptance Criteria 3: if this was the only item in the bag, then the page shows the message for when a bag is empty

# Tasks
 - [x] Add the link/button to remove the item to cart.html template
 - [x] Create view to remove item, and wire it up with url
 - [x] Write Javascript to handle the click event and post the form
 - [x] Test the functionality

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual and automated tests completed. Closed.
