### ISSUE TITLE
USER STORY: Proceed to checkout

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#18]
As a **site user** I can **continue to the checkout process once I've decided on my purchase** so that **I can buy the items**

# Acceptance Criteria
 *  Acceptance Criteria 1:  the user can click on the Checkout button on the cart page, to bring them to the checkout page
 *  Acceptance Criteria 2:  on the checkout page there is a form for the user to fill in their personal info and delivery details
 *  Acceptance Criteria 3: there is also a section for payment details

# Tasks
 - [x] create checkout app, add to installed apps in settings.py, add to project level urls.py
 - [x] create Order model to hold order details, and OrderLineItem model to hold each cart item details
 - [x] add model methods to create order number and calculate totals
 - [x] run migrations
 - [x] create signals.py and add functions to listen for line items being saved or deleted, so that totals can be updated
 - [x] create the OrderForm
 - [x] create the checkout view and add url to urls.py
 - [x] add the url to the secure checkout button in the cart.html template
 - [x] create the template to show the form
 - [x] add CSS as required
 - [x] test manually
 - [x] test the models
 - [x] test the form
 - [x] test the view

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual and automated tests completed. Closed.
