### ISSUE TITLE
USER STORY: Complete a purchase

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#19]
As a **site user** I can **enter my delivery and payment details** so that **I can complete my purchase**

# Acceptance Criteria
 *  Acceptance Criteria 1:  on the checkout page, the user can enter their details into the form including payment details and then submit the details
 *  Acceptance Criteria 2: if the card details are invalid, an error message shows up underneath the payment section
 *  Acceptance Criteria 3: while the form is processing, the page shows that it is processing and the user cannot click anything on the page

# Tasks
 - [x] add stripe's javascript in the base.html template
 - [x] add javascript to create the card element and add it to the checkout form payment details section
 - [x] add CSS as required
 - [x] add button to checkout form
 - [x] add listener to card element so that it checks for errors and shows errors to the user
 - [x] install stripe 
 - [x] create stripe environment variables, add them to settings.py, import to view
 - [x] update checkout view to calculate the total cart amount for stripe and create the payment intent
 - [x] add listener to submit event on checkout form, to prevent submit and send info to stripe + disable the card element
 - [x] update checkout view to create the order in the database 
 - [x] create loading overlay div in checkout.html and add CSS, and update the script to trigger it
