### ISSUE TITLE
USER STORY: Site navigation

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#2]
As a **site user** I can **navigate the site** so that **I can find the page I want to go to**

# Acceptance Criteria
 *  Acceptance Criteria 1:  There should be a site header which is at the top of every page on the website
 *  Acceptance Criteria 2: The logo (website name) should be prominent in the header and it should link back to the home page
 *  Acceptance Criteria 3: The header should contain navigation links to the Shop, Markets and Account, and Cart pages.

# Tasks
 - [x] Create base.html template and create header inside this, add any CSS necessary
 - [x] Will need to create index.html to view on frontend - so create home app, create index.html template, create a view and url so that can see how the header looks on frontend
 - [x] Test the functionality

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manually tested. Only link added so far is to home page, others to be added as pages are built. Did automated test for home page as well. Closed.
