### ISSUE TITLE
USER STORY: Save delivery info while checking out

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#21]
As a **registered user** I can **save my delivery information when checking out** so that **it is saved to my profile for use with my next order**

# Acceptance Criteria
 *  Acceptance Criteria 1:  on the checkout page, if the user is signed in there is a tick box that the user can tick to save their delivery info to their profile
 *  Acceptance Criteria 2: if the user is not signed in, there is a note to tell them they can create an account to save this info/sign in to save info or use saved info
 *  Acceptance Criteria 3: when the box is ticked, the user's profile is updated with this default delivery info
 * Acceptance Criteria 4: if the user goes to make another purchase, when they go to the checkout page then the delivery info is prefilled

This should be linked with #57 

# Tasks
 - [x] create new app for user profiles, add to installed apps in settings.py
 - [x] create UserProfile model with default info fields, add receiver signal so profile created/updated when User model is created/updated, make migrations
 - [x] create a profile view in views.py and add url to urls.py, add app url file to project level urls.py
 - [x] create profile html template that will show saved delivery info - added but profile info to be displayed in form, which will be created in #34 
 - [x] ~~add CSS as needed~~ - to be done with #34  profile info to be displayed in form
 - [x] add the save info checkbox to checkout.html page
 - [x] ~~update the Order model to include the user profile as a foreign key~~ - not needed at this stage
 - [x] update checkout view and checkout success view to save the info if the save profile checkbox was ticked
 - [x] update cache_checkout_data view to add save info variable to the metadata being sent to stripe (created in #57 )
 - [x] update the stripe_elements.js to include a variable for the save info box, when posting to cache_checkout_data view
 - [x] update payment_intent_succeeded webhook handler to update the profile if the save-info box is ticked (need this as this will create the order instead of the checkout view, if the payment goes through but rest of process gets interrupted)
 - [x] update header in base.html to show link to profile page when logged in
 - [x] update checkout view to prepopulate the checkout form with the info saved to the profile (if any)
 - [x] test manually
 - [x] test the model
 - [x] test the view
