### ISSUE TITLE
USER STORY: Order confirmation

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#22]
As a **site user** I can **see an order confirmation page** so that **I know that the order went through okay**

# Acceptance Criteria
 *  Acceptance Criteria 1:  after completing the checkout form and if there were no errors, the user is redirected to a success page confirming the order was successful
 *  Acceptance Criteria 2: the page shows all the order details - order number, date, the items in the order (quantity and item price), the delivery address,  and the totals for the order (total, delivery, grand total) 

# Tasks
 - [x] create checkout_success.html template to display the details 
 - [x] add any CSS as required
 - [x] create the view and add the url path
 - [x] update the checkout view (should be created in #19 ) to redirect to checkout_success url on successful completion of payment
 - [x] test the view
 - [x] test manually

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual and automated testing completed. Closed.
