### ISSUE TITLE
USER STORY: Receive order confirmation email

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#23]
As a **site user** I can **receive an email confirmation of my order** so that **I have this confirmation for my records**

# Acceptance Criteria
 *  Acceptance Criteria 1:  after a user (either anonymous or logged in) successfully places an order, they receive an email confirming the details
 *  Acceptance Criteria 2: the email contains the Order number and shop name in the subject box
 *  Acceptance Criteria 3: the email body thanks the user for their order, and confirms the order date, totals and delivery info.

# Tasks
 - [x] create the .txt files for the email subject and body text
 - [x] write the method in the webhook handler to render the .txt file and send the confirmation email
 - [x] update payment_intent_succeeded to send the email if the order is found, or if the order is created
 - [x] add default sending email to settings.py
 - [x] test manually - order will be only shown in console for now as still in development environment

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual testing completed with email logging to console. Closed.
