### ISSUE TITLE
USER STORY: View list of upcoming markets

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#24]
As a **site user** I can **easily view all the upcoming markets** so that **I can plan if I want to attend one of the markets**

# Acceptance Criteria
 *  Acceptance Criteria 1:  A user can go to the Markets page of the website and it displays a list of the upcoming markets
 *  Acceptance Criteria 2: Only markets that are not in the past are shown
 *  Acceptance Criteria 3: The details shown for each market are: name, location, date, times, website and an image

# Tasks
 - [x] Create markets app, add to installed apps
 - [x] Create market model and county model, make migrations
 - [x] Create template for markets page
 - [x] Create view and url, add urls for markets app to project urls.py
 - [x] Add the url to the site header in base.html, and in the link in the learn-more section on home page
 - [x] Test the models
 - [x] Test the view
 - [x] Manually test

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual and automated testing completed. Closed.
