### ISSUE TITLE
USER STORY: Sort markets list

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#25]
As a **site user** I can **sort the markets list** so that **I can find what I'm looking for more easily**

# Acceptance Criteria
 *  Acceptance Criteria 1:  there is an option in the markets page menu bar to sort the markets
 *  Acceptance Criteria 2: the user can choose one of these options, and the markets are sorted according to the choice
 *  Acceptance Criteria 3: the choices should be: by name (A to Z), by name (Z to A), by date (ascending), by date (descending)

# Tasks
 - [x] add sub header to markets.html for sorting options
 - [x] update the show_markets view to handle the sorting requests and return the markets sorted as per the request
 - [x] add script to update url based on selected sorting option so that get request is passed to the view
 - [x] test the view
 - [x] test manually

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual and automated testing completed. Closed.
