### ISSUE TITLE
USER STORY: Save a market to profile

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#26]
As a **registered user** I can **save a market that I want to go to** so that **I don't forget about it as it will be in my profile**

# Acceptance Criteria
 *  Acceptance Criteria 1:  A user who is logged in can see a button on each market card in the markets page
 *  Acceptance Criteria 2: The button allows them to save the market to their profile
 *  Acceptance Criteria 3: After clicking the button to save the market, the user can see a success message

# Tasks
 - [x] create SavedMarket model, make and run migrations
 - [x] Create the view and url to add a saved market
 - [x] Add the button to the markets page
 - [x] Test manually
 - [x] Test the model
 - [x] Test the view

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual and automated testing done. Renamed model to SavedMarketList. Closed.
