### ISSUE TITLE
USER STORY: See if a market is saved or not

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#27]
As a **registered user** I can **see if I have saved a market already when viewing the markets list** so that **I know if it's already saved in my profile or not**

# Acceptance Criteria
 *  Acceptance Criteria 1:  when a user is logged in and is on the markets page, each market card has a button, the text on the button is different depending on whether the user has saved the market or not
 *  Acceptance Criteria 2: if the market is not saved, the button says 'save market to profile' (or similar)
 *  Acceptance Criteria 3: if the market is saved, then the button text is 'remove market from profile' (or similar)

# Tasks
 - [x] Update the show markets view to pass back the saved markets list for the user if it exists
 - [x] Update markets.html to show the correct text on the button, depending on whether market is saved or not
 - [x]  Add CSS as required
 - [x] Test manually
 - [x] Update tests for show markets view

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual testing completed. Closed.
