### ISSUE TITLE
USER STORY: Remove a market from profile

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#28]
As a **registered user** I can **remove a previously saved market from my profile** so that **it is no longer in my profile if I don't want to go to it**

# Acceptance Criteria
 *  Acceptance Criteria 1:  when a user is logged in and on the Markets page, the markets they have saved have a button called 'remove market from profile' (or similar) see #27 
 *  Acceptance Criteria 2: the user can click on this button to remove the market from their saved markets
 *  Acceptance Criteria 3: a success message is displayed and the market in the Markets page now has a button for 'save market'

# Tasks
 - [x] update the add_saved_market view to handle removing market also (should be able to use same view for this: if market on the list, then remove it, otherwise add it. If list does not exist, create it. If nothing left on list, delete the list.)
 - [x] if using same view, then rename the view and rename the url, update url in html template
 - [x] test manually
 - [x] test the view

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual and automated testing completed. Closed.
