### ISSUE TITLE
USER STORY: Sign up for an account

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#29]
As a **site user** I can **sign up for an account** so that **I can enjoy the benefits of having an account e.g. saving delivery info**

# Acceptance Criteria
 *  Acceptance Criteria 1:  the sign up page opens after the user clicks on link from header to sign up
 *  Acceptance Criteria 2:  the sign up form contains the fields for the user to register - username, email address, email address confirmation, password, confirm password and Submit button
 *  Acceptance Criteria 3: the form doesn't submit unless the required fields are completed or if there are errors in the inputs
 * Acceptance Criteria 4: after the form is submitted successfully, the email verification page is displayed, see #30 

# Tasks
 - [x] install allauth, set up allauth urls, add to settings, run migrations
 - [x] update header in base.html with the url to sign up
 - [x] amend the allauth templates so that styling matches rest of site
 - [x] test functionality

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Email shows up in terminal (for dev - will be amended later in production to send real email). After verifying email, page redirects to sign in page. Closed.
