### ISSUE TITLE
USER STORY: Find the social media account

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#3]
As a **site user** I can **find the Knot Art social media accounts** so that **I can follow them on social media to keep up to date**

# Acceptance Criteria
 *  Acceptance Criteria 1:  The links to the social media accounts should be in the footer on each page, represented by their icons
 *  Acceptance Criteria 2: The links are external, so open in a new window
 *  Acceptance Criteria 3: The links are for the Facebook business page, Twitter, Instagram and LinkedIn

# Tasks
 - [x] Create the footer in base.html
 - [x] Add the social media links
 - [x] Complete the styling
 - [x] Manually test to ensure links open in new window and are wired up correctly. Facebook business page not created yet, so link will need to be updated later on, new user story created #49

**Comment by Fiona-T** [comment]
Tasks completed and acceptance criteria met. Tested manually to ensure links open in new window and linked correctly.  Closed.
