### ISSUE TITLE
USER STORY: Receive email on sign up

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#30]
As a **site user** I want to **receive an email confirmation when I register** so that **I know my account registration was successful and secure**

# Acceptance Criteria
 *  Acceptance Criteria 1:  After filling in the sign up form (see #29 ) the user is redirected to a page confirming an email was sent for them to verify their email address
 *  Acceptance Criteria 2:  There should be an email received by that email address, providing a link to be used to verify the email address
 *  Acceptance Criteria 3: The link brings the user to a new page where they can press a button to confirm the email address
 * Acceptance Criteria 4: after pressing the button, the user is brought to the sign in page to sign in

# Tasks
 - [x] Set up app password on email account to send emails
 - [x] Add password and email host address to heroku config vars
 - [x] Update settings.py to use the email host in production/continue to print to terminal in dev
 - [x] Update domain name and display name for Site in admin site, so it displays on the emails
 - [x] deploy to heroku
 - [x] test manually

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manually tested from deployed site. Closed.
