### ISSUE TITLE
USER STORY: Sign into account

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#31]
As a **registered user** I can **sign into my account** so that **I can access my profile**

# Acceptance Criteria
 *  Acceptance Criteria 1:  the sign in page opens after the user clicks on link from header to sign in
 *  Acceptance Criteria 2:  the sign up form contains the fields for the user to sign in - username or email address, and password - and Sign in button
 *  Acceptance Criteria 3: After submitting the form, the user is redirected to the home page

# Tasks
 - [x] allauth should be installed as part of #29 and template styling done
 - [x] add link to site header in base.html for sign in 
 - [x] update settings to ensure page redirects after sign in
 - [x] test the functionality

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Can sign in with either username or email. Redirects to home page after sign in. Closed.
