### ISSUE TITLE
USER STORY: Sign out of account

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#32]
As a **registered user** I can **sign out of my account when finished** so that **I know I am signed out securely**

# Acceptance Criteria
 *  Acceptance Criteria 1:  When a user is signed in, the Sign Out link is present in the header from underneath the Account section
 *  Acceptance Criteria 2:   After clicking the Sign Out link, the Sign Out page opens
 *  Acceptance Criteria 3: Sign Out page has text asking user to confirm they want to sign out, and a button
 * Acceptance Criteria 4: After signing out, the user is redirected to the home page

# Tasks
 - [x] update site header in base.html to show sign out link when user is signed in
 - [x] update settings with sign out redirect url
 - [x] styling of allauth templates should be done in #29 but check in case any tweaks needed
 - [x] test the functionality

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Header changes to have Sign Out dropdown once signed in. Redirects to home page after sign out. Closed.
