### ISSUE TITLE
USER STORY: Know if signed into account or not

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#33]
As a **registered user** I can **easily see if I am signed into my account or not** so that **I know straight away if I need to sign in**

# Acceptance Criteria
 *  Acceptance Criteria 1:  When a user is not signed in, there is a menu item in the main page navigation called Sign In. This menu item changes to 'Account' when the user is signed in (and the menu dropdown items change accordingly)
 *  Acceptance Criteria 2: When the user is signed in, the header contains a note that they are "signed in as username"
 *  Acceptance Criteria 3: When signed in, the My Profile page shows the user's name
 * Acceptance Criteria 4: On the checkout page, if the user is not signed in there is a note telling them they can sign in to use their saved default delivery info. (If they are signed in, then their default delivery info if any is populated on the delivery details, as per #21 )
 * Acceptance Criteria 5: When viewing the Markets page, if the user is not logged in then they see a note saying Sign in to save the market, if they are signed in then they see a button to save the market or remove it (already done as part of #27 )

# Tasks
 - [x] Update the header in base.html to show the user name when signed in
 - [x] check other pages to ensure content still visible now that header has an extra row
 - [x] Styling - add a down arrow to the menu dropdown so it is clear this is a dropdown menu (other items in header are just links, so to distinguish this one). And add filled icon when signed in, to further differentiate from the signed out version
 - [x] Update profile.html to show the user name
 - [x] Update checkout.html to show note if not signed in
 - [x] Test manually

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. All html templates updated with pt-3 on header column so contents sit below the bigger header.  Manually tested each part of functionality. Closed.
