### ISSUE TITLE
USER STORY: View order history

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#35]
As a **registered user** I can **see my previous orders in my profile** so that **I can see all the orders I made and can find details of a previous order**

# Acceptance Criteria
 *  Acceptance Criteria 1:  when a user is signed in and goes to their profile page, they can see their order history
 *  Acceptance Criteria 2: if there are no previous orders, there is a note stating this and a link to the shop
 *  Acceptance Criteria 3: if there are previous orders, these are listed with the newest first and show the order number, date, items and quantity, and final total

# Tasks
 - [x] add user profile to Order model so that user can be added to Order instance, make migrations
 - [x] add user profile field to Order admin 
 - [x] update checkout_success view to attach the user to the order when created
 - [x] update webhook handler payment_intent_succeeded to attach user to order when created
 - [x] update the profile view to get the orders for the user and pass them in the context
 - [x] update the profile.html template to render the order history
 - [x] test manually
 - [x] update the tests for profile view

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual and automated testing completed. Closed.
