### ISSUE TITLE
USER STORY: Remove a saved market

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#37]
As a **registered user** I can **remove a previously saved market from my profile** so that **it is no longer in my profile if I don't want to go to it**

# Acceptance Criteria
 *  Acceptance Criteria 1:  when a user is logged in and on the My Markets page in the Account section, each market shown there has a button for 'remove from profile' (or similar wording)
 *  Acceptance Criteria 2: clicking the button removes the market from their profile and they see a success message
 *  Acceptance Criteria 3: the market no longer appears in their My Markets page

Note - linked to #28 which is to remove the market via the main Markets page

# Tasks
 - [x] use the view that has been created in #28 
 - [x] add hidden input so view can redirect back to either my_markets or markets page depending on where the button was clicked
 - [x] add the url to the button in my markets page
 - [x] test manually

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual testing completed. Closed.
