### ISSUE TITLE
USER STORY: Shop owner view all products including inactive ones

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#38]
As a **website owner** I can **view all the products in the shop, even if they are not active,** so that **I can see an overview of all products, and so that I can edit inactive products**

# Acceptance Criteria
 *  Acceptance Criteria 1: When a superuser is logged in, they can see all items in the shop, even those that are not active
 *  Acceptance Criteria 2: The card for each product also displays the active status (this is not shown on the normal view for regular or anonymous users) 

# Tasks
 - [x] Update the products html template, to include the is_active flag in the card for each product, if the user is a superuser
 - [x] Update the view to show all products if the user is a superuser
 - [x] Add new tests to test_views.py to test for this, and manually test
 - [x] Also need to update product_details.html template to show is_active flag for superuser
 - [x] And update product_details view to ensure that a non superuser cannot access a url to view a non active product

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Updated tasks to include equivalent tasks on product_details page. Manual and automated testing completed. Closed.
