### ISSUE TITLE
USER STORY: Add a new product to shop

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#39]
As a **website owner** I can **add a new product to the shop** so that **I can sell the product to customers**

# Acceptance Criteria
 *  Acceptance Criteria 1:  when the admin user is logged in, they have an option under the Account menu for Product Management
 *  Acceptance Criteria 2: when they go to this page, there is a form to Add a Product
 *  Acceptance Criteria 3: the fields on the form are: category dropdown, sku, name, description, price, image and check boxes for active product and new product
 * Acceptance Criteria 4: the product name must not be the same as an existing product name
 * Acceptance Criteria 5: the active and new checkboxes default to checked and the image field is optional (as the no-image file will show up for the product if there is no image attached)
 * Acceptance Criteria 6: after adding the product (and assuming the active flag is ticked), the product shows up in the shop page for users to buy

# Tasks
 - [x] create the product form
 - [x] create the add product view and url
 - [x] add url to the main header under Account dropdown if user is superuser
 - [x] create the add product template
 - [x] update the view to handle posting the form
 - [x] test manually
 - [x] test the form
 - [x] test the view

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual and automated testing completed. Closed.
