### ISSUE TITLE
USER STORY: Sign up to newsletter

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#4]
As a **site user** I can **sign up to the newsletter** so that **I can stay informed  and stay engaged with the shop**

# Acceptance Criteria
 *  Acceptance Criteria 1:  The footer on each page should contain a form to sign up for the newsletter
 *  Acceptance Criteria 2: The form consists of one field for email address, and a button to sign up
 *  Acceptance Criteria 3:  After submitting the form, the email address submitted is added to the subscribers list in mailchimp

Note: needs deployed website url before MailChimp can be set up

# Tasks
 - [x] Create newsletter sign up form on Mailchimp
 - [x] Add it to the footer in base.html
 - [x] Tidy up the Javascript and CSS supplied by Mailchimp so they are in the correct locations
 - [x] Adjust the CSS if needed
 - [x] Manually test the form
 - [x] Add link to newsletter from home page About Us section

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Changed Mailchimp provided code to fit into footer as inline form + not using Mailchimp CSS. Tested invalid inputs to form, Mailchimp script handles this (and using their CSS for this). Tested valid inputs and contacts appear in Mailchimp contacts dashboard. Closed.
