### ISSUE TITLE
USER STORY: Edit a product in the shop

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#40]
As a **website owner** I can **edit the details of a product in the shop** so that **I can change the price, description etc. and customers will see the updated information**

# Acceptance Criteria
 *  Acceptance Criteria 1:  When admin user is signed in, they can see an Edit link/button on the products in the shop on both the main shop page and in the product details page
 *  Acceptance Criteria 2: Clicking the link brings them to the edit product page which displays a form with the existing details pre-populated (same form as the add product form in #39 )
 *  Acceptance Criteria 3: The user can change the details as needed and submit the form
 * Acceptance Criteria 4: Once submitted successfully the page redirects to the product details page for that product with the updated details

# Tasks
 - [x] create edit_product.html template
 - [x] add CSS as required
 - [x] create the view and the url
 - [x] add the url link to the product card on products page, and in product details page
 - [x] add the custom widget for the image upload field, update forms.py to use it
 - [x] update the view to handle the post request
 - [x] test manually
 - [x] test the view
