### ISSUE TITLE
USER STORY: Toggle active flag on product in shop

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#41]
As a **website owner** I can **turn on or off the active flag on a product** so that **I can add or remove it from appearing in the shop for customers when it is in/out of stock**

# Acceptance Criteria
 *  Acceptance Criteria 1:  when the admin user is logged in, they can see a tick box beside Active product for all products in the shop and in the product details page
 *  Acceptance Criteria 2: they can tick the box to make it Active (and product appears in shop for regular users)
 *  Acceptance Criteria 3:  they can untick the box to make it Not Active (and product does not appear in the shop for regular, non-admin, users)

# Tasks
 - [x] write the view to handle the toggle, and create url
 - [x] add url to the product and product_details templates along with the checkbox
 - [x] test manually
 - [x] test the view

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Toggle is done by button not checkbox, as more user friendly. Manual and automated testing completed. Closed.
