### ISSUE TITLE
USER STORY: Delete a product from the shop

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#42]
As a **website owner** I can **delete a product** so that **it will not appear in the shop if it was added in error**

# Acceptance Criteria
 *  Acceptance Criteria 1:  When admin user is signed in, they can see a Delete link/button on the products in the shop on both the main shop page and in the product details page
 *  Acceptance Criteria 2: Clicking the link brings up a confirmation box where they can either Cancel to go back, or press Confirm to confirm the deletion. The confirmation box shows the summary details of the product they are about to delete.
 *  Acceptance Criteria 3: Once deleted, the product no longer appears in the shop

# Tasks
 - [x] create the view and the url
 - [x] create the delete html modal
 - [x] add CSS as needed
 - [x] add the delete link to the products and product details html templates
 - [x] test manually
 - [x] test the view

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual and automated testing completed. Closed.
