### ISSUE TITLE
USER STORY: Shop owner view all markets including past ones

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#44]
As a **website owner** I can **see all markets on the markets page including past ones** so that **I can see an overview of all markets and see older markets as well as upcoming ones**

# Acceptance Criteria
 *  Acceptance Criteria 1: when the admin user is signed in, they can see all of the markets, including those that are in the past
 *  Acceptance Criteria 2: a regular user or anonymous user can only see markets that are not in the past
 *  Acceptance Criteria 3: for the admin user, there is an extra note on the card for the market to highlight that it is in the past

# Tasks
 - [x] update the view to show all markets if user is superuser
 - [x] update markets page to include a note to show if market is in the past
 - [x] test manually
 - [x] update the tests for the view to test this functionality

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Added model property for date_passed, so updated model tests as well. Manual and automated testing completed. Closed.
