### ISSUE TITLE
USER STORY: Add a new market to markets page

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#45]
As a **website owner** I can **add a new market to the markets page** so that **customers are informed of the market**

# Acceptance Criteria
 *  Acceptance Criteria 1:  when the admin user is signed in, they have an option under the Account dropdown for Markets Management
 *  Acceptance Criteria 2: when they go to this page, there is a form to Add Market
 *  Acceptance Criteria 3: the fields on the form are all fields that are on the market model, and a button to submit
 * Acceptance Criteria 4: the market date must be in the future
 * Acceptance Criteria 5: after adding the market, the page redirects to Markets page and the new market is visible for users
 * Acceptance Criteria 6: the start date must be before the end date and an error displays if not

# Tasks
 - [x] create MarketForm 
 - [x] create  add market view and url
 - [x] create html template
 - [x] add CSS as required
 - [x] add url to Account dropdown for superuser
 - [x] update the view to handle posting of the form
 - [x] add date validation to form
 - [x] test the form
 - [x] test manually
 - [x] test the view

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual and automated testing completed. Closed.
