### ISSUE TITLE
USER STORY: Edit details of a market 

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#46]
As a **website owner** I can **edit the details of a market in the markets page** so that **customers will see the updated information**

# Acceptance Criteria
 *  Acceptance Criteria 1:  when the admin user is signed in, they can see an Edit link/button on the markets in the Markets page
 *  Acceptance Criteria 2: this brings the user to a page with a form pre-populated with the existing details, where they can make changes and submit the form
 *  Acceptance Criteria 3: once submitted, the page redirects back to the markets page

# Tasks
 - [x] create edit market view and url
 - [x] create html template for edit market page
 - [x] add CSS as needed
 - [x] add the url to the markets card on markets.html
 - [x] update the view to handle the post request
 - [x] test manually
 - [x] test the view

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual and automated testing completed. Closed.
