### ISSUE TITLE
USER STORY: Delete a market

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#47]
As a **website owner** I can **delete a market** so that **it will not appear in the markets page if it was added in error**

# Acceptance Criteria
 *  Acceptance Criteria 1:  when the admin user is signed in, they can see a Delete link/button on the markets in the Markets page
 *  Acceptance Criteria 2: this brings up a confirmation box showing summary details of the market and two buttons - Cancel or Delete 
 *  Acceptance Criteria 3: once deleted, the market no longer appears in the Markets page

# Tasks
 - [x] create the view and the url
 - [x] create the delete market modal html
 - [x] add CSS as needed
 - [x] add the delete url to the markets card on markets.html
 - [x] test manually
 - [x] test the view

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual and automated testing completed. Closed.
