### ISSUE TITLE
USER STORY: Facebook business page

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#49]
As a **website owner** I have **a link to the Facebook business page on the website** so that **customers or visitors to the website can follow the facebook page and I can generate more business through the facebook page**

# Acceptance Criteria
 *  Acceptance Criteria 1: There is a link in the footer for the business facebook page, which opens in a new tab

# Tasks
 - [x] create the facebook page, add description, link it to the website, add a welcome post
 - [x] update the link in the footer in base.html
 - [x] test that the link works and opens in new tab
