### ISSUE TITLE
USER STORY: Custom 404 page

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#5]
As a **site user** I can **see a 'Page not found' page with consistent branding to the rest of the site, when I try to access a page in error** so that **I can find my way back to the website and know I have not left the website**

# Acceptance Criteria
 *  Acceptance Criteria 1:  the 404 page not found that is displayed to the user is consistent with the branding on the rest of the website
 *  Acceptance Criteria 2: the page contains the header and footer as per the rest of the website
 *  Acceptance Criteria 3: the page contains a short note to the user explaining the page wasn't found, along with links for them to get back to the main website

# Tasks
 - [x] create the html template
 - [x] add any CSS as necessary
 - [x] Test to ensure the page displays if an incorrect url is typed in

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manually tested. Closed.
