### ISSUE TITLE
USER STORY: Have keywords in metadata

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#50]
As a **website owner** I have **relevant keywords included in the webpage metadata** so that **it helps improve SEO so that users searching for these keywords can find my website**

# Acceptance Criteria
 *  Acceptance Criteria 1: there is a meta keywords element in the head of the html, and this contains all relevant keywords
 *  Acceptance Criteria 2: there is a meta description element in the head of the html, and this contains a description of the website and uses some keywords

# Tasks
 - [x] keywords should have been defined in #48 
 - [x] update the head element in base.html with the meta tag for description and include keywords
 - [x] update the head element in base.html with the meta tag for keywords and include all keywords

**Comment by Fiona-T** [comment]
tasks completed and acceptance criteria met. Closed.
