### ISSUE TITLE
USER STORY: Admin site for Products app

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#51]
As a **site owner** I can **access the Django admin site for the products** so that **I can view, edit, delete products from here as well as from the website**

# Acceptance Criteria
 *  Acceptance Criteria 1:  The admin user can go to the django admin site and view the products and categories tables inside the products app.
 *  Acceptance Criteria 2:  For the categories table, the category name and friendly name are displayed in the list view
 *  Acceptance Criteria 3: For the products table, the list view shows product name, sku, category, price, if new, if active. 
 * Acceptance Criteria 4: In the list view for products, the user can filter by category, by the active flag and by the new flag
 * Acceptance Criteria 5: the user can add, edit and delete products and categories from this view (default Django functionality)
 * Acceptance Criteria 6: the user can amend the is_active flag from list view, and can search by product name

# Tasks
 - [x] create superuser to access admin site, add site name to settings
 - [x] create admin class for category model in admin.py
 - [x] create admin class for product model in admin.py
 - [x] manually test the functionality in the admin site

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual testing done in admin site. Closed.
