### ISSUE TITLE
USER STORY: See preview of shopping cart

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#54]
As a **user** I can **see a preview of my shopping cart when I make changes** so that **I can easily see the new cart**

# Acceptance Criteria
 *  Acceptance Criteria 1:  when a user takes any action relating to the shopping cart, a small preview of the shopping cart appears alongside the confirmation message
 *  Acceptance Criteria 2: the preview shows the number of items in the cart, and for each item the image, product name and quantity. The totals are shown at the bottom, along with a link to go to the cart page to checkout
 *  Acceptance Criteria 3: the preview is shown when the user adds to cart, adjusts quantity, or removes an item

# Tasks
 - [x] add html to show the shopping cart preview for the success toast
 - [x] Add CSS as required
 - [x] Test the functionality
