### ISSUE TITLE
USER STORY: View details of a previous order

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#58]
As a **registered user** I can **view details of a previous order** so that **I can check what was ordered and where it was delivered to**

# Acceptance Criteria
 *  Acceptance Criteria 1:  a logged in user who has previous orders can go to their order history and click on an order to view the full details
 *  Acceptance Criteria 2: the order number links to the details page
 *  Acceptance Criteria 3: the details displayed are the same as those displayed in the checkout success page.

# Tasks
 - [x] update profile page to include a link to the order details and create url 
 - [x] create the view for the order detail, using the checkout_success.html template since it is the same information
 - [x] include a note that this is a past order not a current one
 - [x] test the view

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Amended checkout_success.html to show different heading/intro if coming from profile page, so no need for toast message. Manual and automated testing done and view restricted to logged in user and user who is attached to that order. Closed.
