### ISSUE TITLE
USER STORY: Find terms of use and privacy policy

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#6]
As a **site user** I can **find the terms of use and privacy policy** so that **I can read these documents and have trust in the site**

# Acceptance Criteria
 *  Acceptance Criteria 1:  The links to the Terms of Use and Privacy Policy are present in the footer on each page
 *  Acceptance Criteria 2:  The links are internal so open in same window
 *  Acceptance Criteria 3: Each link contains the correct policy

Note: needs deployed website url in order to generate the policies

# Tasks
 - [x] Generate the terms of use
 - [x] Generate the privacy policy
 - [x] Add the links to the footer
 - [x] Add any CSS as needed
 - [x] Test manually

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual testing done. Closed.
