### ISSUE TITLE
USER STORY: Filter markets by County

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#60]
As a **user** I can **select a county to filter the markets by** so that **I can easily see just the markets in that particular county**

# Acceptance Criteria
 *  Acceptance Criteria 1:  in the markets page, the sub header has a dropdown of counties that the user can select from
 *  Acceptance Criteria 2: the default is all counties
 *  Acceptance Criteria 3: when a particular county is selected, only the markets in that county are shown
 * Acceptance Criteria 4: the options are the counties in Ireland plus the areas in Dublin (Dublin 1, 2 etc.)

# Tasks
 - [x] update markets.html with box to select county 
 - [x] add CSS as required
 - [x] update show_markets view to show the markets for the selected county if there is a request to filter by a county
 - [x] update the card on markets.html to link to the filtered by county markets
 - [x] update markets.html to show the results of the filtering by county i.e. number of markets returned for that county
 - [x] test manually
 - [x] update tests for the show_markets view

**Comment by Fiona-T** [comment]
All tasks completed. Acceptance criteria tweaked - for better UX, restricted dropdown list to the counties that currently exist in the markets queryset returned from db, so that the user does not select a county that returns no results. Also currently selected county is shown in the dropdown list, or All if none. Manual and automated testing completed. Closed
