### ISSUE TITLE
USER STORY: Sort markets list on My Markets page

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#61]
As a **registered user** I can **sort the markets list in My Markets page** so that **I can find the market I'm looking for more easily**

# Acceptance Criteria
 *  Acceptance Criteria 1:  there is an option in the My Markets page menu bar to sort the markets
 *  Acceptance Criteria 2:  the user can choose one of these options, and the markets are sorted according to the choice
 *  Acceptance Criteria 3:  the choices should be: by name (A to Z), by name (Z to A), by date (ascending), by date (descending)

# Tasks
 - [x] add select sorting box to my_markets.html 
 - [x] update the show_saved_markets view to handle the sorting requests and return the markets sorted as per the request (re-using function already in script.js) 
 - [x] test the view
 - [x] test manually

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual and automated testing completed. Closed.
