### ISSUE TITLE
USER STORY: Custom pages for 403, 405 and 500 http errors

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#62]
As a **user** I can **see a page styled the same way as the website when I get a server error or access denied ** so that **I can find my way back to the correct page on the website**

# Acceptance Criteria
 *  Acceptance Criteria 1:  the pages displayed to the user for a 403 (permission denied), and 500 (server error) are consistent with the branding on the rest of the website
 *  Acceptance Criteria 2: the pages contain the header and footer as per the rest of the website
 *  Acceptance Criteria 3: the pages contains links for them to get back to the main website

Note: 404 page already covered under previous user story: #5 

# Tasks
 - [x] create the html templates for 403 and 500 
 - [x] add any CSS as necessary
 - [x] Test with the views that raise these errors, to ensure the page is displayed when debug is false

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual testing completed. Closed.
