### ISSUE TITLE
USER STORY: Edit details of a past market

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#64]
As a **website owner** I can **edit the details of a past market** so that **I can still edit the details even though it is in the past**

# Acceptance Criteria
 *  Acceptance Criteria 1:  when the admin user is logged in, they can go to Edit a market for an existing market that has a date in the past
 *  Acceptance Criteria 2: the admin user can save updates to the market even though the existing date is in the past
 *  Acceptance Criteria 3: However they cannot edit the date to be in the past (as the purpose of this feature is to allow details of a past market to be edited, but if it is not in the past there should be no need to amend the date to be in the past)
 * Acceptance Criteria 4: there is a notification box alerting them that they are editing a past market and can change the details but if changing date can only change it to a future date
 * Acceptance Criteria 5: there is helptext under the date field advising of this also

# Tasks
 - [x] update themarket form clean method to check if the date was in the past, and allow the edits if so, and to change the helptext
 - [x] update the edit market view to show the alert
 - [x] test manually
 - [x] update tests for the form
 - [x] update tests for the view

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual and automated testing complete. Closed.
