### ISSUE TITLE
ISSUE: Need to add list of available counties for use when creating markets

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#65]
Add the list of Irish counties and Dublin areas to the database before markets are created so that the market instances can use the counties. 

# Tasks
 - [x] Get the complete list of counties and Dublin areas
 - [x] Add these to the database - tbc if using fixtures or not
 - [x] Manually test that they are available when adding a market
 - [x] Update the Add Market form so they appear in alphabetical order and add a blank label to the dropdown

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Updated County model with ordering, and MarketForm with blank choice label. Manual testing completed. Closed.
