### ISSUE TITLE
USER STORY: Generate sku for products

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#66]
As a **website owner** I can **add a product and the sku is created automatically** so that **the skus for the products are standardised and I do not have to manually add a sku**

# Acceptance Criteria
 *  Acceptance Criteria 1: When a new product is created, a sku is automatically added to the product
 *  Acceptance Criteria 2: The sku is 10 characters and consists of the first three letters from the category, followed by a dash and the id of the product, preceded by leading zeros to make up the 10 characters
 *  Acceptance Criteria 3: The sku does not appear on the Add Product page form since it is automatically generated

# Tasks
 - [x] Update the Products model in models.py - amend the sku field, and create a method to generate the sku
 - [x] Add the post save method so that the id of the product can be used in the sku (id not available when saving initially)
 - [x] Test manually
 - [x] Update tests for the model

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual testing done and updated test_models and test_forms with changes. Closed.
