### ISSUE TITLE
USER STORY: View all products in shop

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#7]
As a **site user** I can **easily view all the products in the shop** so that **I can see all the available products immediately without having to sort or filter or take any action**

# Acceptance Criteria
 *  Acceptance Criteria 1:  When a user goes to the Shop page, they are presented with all products on the page
 *  Acceptance Criteria 2:  The user does not have to do anything, the default is that all products are listed
 * Acceptance Criteria 3:  Only products that are 'active' should be displayed
 * Acceptance Criteria 4:  The details shown for each product should be: name, image, price, category

# Tasks
 - [x] Create products app, add to project level urls, add to installed apps in settings
 - [x] Create category model and product model, make migrations
 - [x] Create html template
 - [x] Create the view to display the page, and create the url
 - [x] Link up url in the site header in base.html and in 'learn-more' section in home app index.html 
 - [x] Test the view 
 - [x] Test the models

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Default image added also, and badge for new products. Automated and manual tests done. Closed.
