### ISSUE TITLE
ISSUE: Fix style for notification box

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#72]
The messages notification box that displays the toast messages needs to be reviewed in terms of style. Positioning needs to be adjusted. Perhaps remove the arrow from the top of the box since the messages are to do with different sections of the website, so having the arrow pointing near the cart icon doesn't work well for messages to do with adding/editing products for the admin user, or for notifications to do with signing in/out, or markets.

# Tasks
 - [x] review the notification box positioning and update the CSS
 - [x] review the notification box arrow + whether it should be removed, and update the CSS if so
 - [x] test manually for different screen sizes

**Comment by Fiona-T** [comment]
All tasks completed. Adjusted header on larger screens so it is full width, so positioning of toast box against it works better on all sizes. Manually tested for responsiveness using dev tools. Also added aria attributes to toast container (base.html) and to each div with class toast in the toast html templates - polite for info and success, assertive for error and warning. Closed.
