### ISSUE TITLE
ISSUE: Toast notifications for markets - amend so they do not show bag info

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#73]
Update the toast success message so that it doesn't show the bag info when a user saves a market. So that this is consistent with the message shown for changes to the profile - bag info not shown.

# Tasks
 - [ ] ~proposed approach: amend views that are not related to the bag, to have a context item of 'do_not_show_bag_in_toast' with a value of True~
 - [x]  instead of the above, amend the views where success messages are shown for the bag, include an `extra_tags=` in the message, which can then be used as a conditional in the toast template
 - [x] update the toast_success template to show bag if the extra_tags to show the bag are present, and if there is a grand total
 - [x] remove the 'on_profile_page' Boolean from the context in the profile view, this will no longer be required (it was being used in the toast template to only show the bag if not on profile page, however we are now extending this functionality and changing the approach as outlined above)
 - [x] test manually
 - [x] update the tests for the views that were amended

**Comment by Fiona-T** [comment]
There were more views with success messages not related to the bag, than views related to the bag, so amended the approach to update the success messages for the views related to bag updating. These views don't have contexts and are redirect not render, so added extra_tags in the message instead. Manual and automated testing completed. Closed.
