### ISSUE TITLE
USER STORY: Filter saved markets by county

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#74]
As a **registered user** I can **filter my saved markets by county** so that **I can easily see just my saved markets in that particular county**

# Acceptance Criteria
 *  Acceptance Criteria 1:  in the my_markets page, if the user has saved markets, the sub header has a dropdown of counties that the user can select from
 *  Acceptance Criteria 2: the default is all counties and the counties available to select from are the counties that exist for the saved markets only (so no filter returns 0 results)
 *  Acceptance Criteria 3: when a particular county is selected, only the markets in that county are shown

# Tasks
 - [x] update the show_saved_markets view to handle filtering by county
 - [x] update the markets_sort_and_filter includes template to use the my_markets url in the dropdown box, or the markets url, depending on where the filter request comes from
 - [x] import the markets.css to the my_markets.html page to use the specific stying for the dropdown box
 - [x] update tests for show_saved_markets view
 - [x] test manually

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met, manual and automated testing completed. Closed.
