### ISSUE TITLE
USER STORY: Add comments to a market

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#78]
As a **registered user** I can **add a comment to a market** so that **I can share my views on a market with other users**

# Acceptance Criteria
 *  Acceptance Criteria 1:  When a sign in user is on the market details page, there is a text box for them to leave a comment, and a button to submit the comment
 *  Acceptance Criteria 2: If the user is not logged in, then there is a note advising to sign in/register in order to comment
 *  Acceptance Criteria 3: After submitting the comment the page updates and the comment is now visible on the market

# Tasks
 - [x] Create the Comment form
 - [x] Update the market_details.html page to show the form if the user is logged in/show note if not
 - [x] Update the market_details view to include the form in the context
 - [x] Add CSS as needed
 - [x] Update the market_details view to handle posting of the comment form
 - [x] test manually
 - [x] test the form
 - [x] test the view

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual and automated testing completed. Added validation on the comment length also. Closed.
