### ISSUE TITLE
ISSUE: Remove 'image_url' field from Product and Market models, not being used

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#79]
This field is not required as it would only be needed if linking the images to another url which is not the case in this project. The market images link to the external market website and the product images do not link to anything (on shop page they link to the product details page)

# Tasks
 - [x] Remove the field from Product model in models.py and make/run migrations to both databases
 - [x] Remove the field from Market model in models.py and make/run migrations to both databases
 - [x] Re-run test_models.py in products and markets app to ensure all OK
 - [x] Manually test to ensure no issues on the shop/market pages as a result of the changes (should not be)

**Comment by Fiona-T** [comment]
Removed field from both models and did migrations to development and production databases. Field was null for all records. Tested manually, removed field from test_forms.py in products app (for tests with non-required fields). Re-ran all tests, all okay. Closed.
