### ISSUE TITLE
USER STORY: See how many comments are on a market

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#80]
As a **user** I can **see how many comments are on a market** so that **I can decide if I want to read them or not**

# Acceptance Criteria
 *  Acceptance Criteria 1:  on the markets page, each market shows the number of comments
 *  Acceptance Criteria 2: or if there are no comments, it shows 'Be the first to comment' or similar
 *  Acceptance Criteria 3: clicking on the number of comments will bring the user to view a market details page (to be created in separate user story #81 )

# Tasks
 - [x] Create the Comment model in the markets app models.py, make and run migrations to both databases
 - [x] Add to admin site so some comments can be created from there for manual testing
 - [x] Add a section on the markets.html page to display the number of comments for the market
 - [x] Add CSS as needed
 - [x] Test manually
 - [x] Add the comments section on the market card to the my_markets.html page (profiles app) also
 - [x] Test the model

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Link created to show number of comments or 'be the first to comment', but will not be linked up until #81 is done. Manual and automated testing done. Closed.

**Comment by Fiona-T** [comment]
Edit: confirm migrations done on the Postgres production database for the new model also.
