### ISSUE TITLE
USER STORY:  View the comments on a market

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#81]
As a **user** I can **read all the comments on a market** so that **I can see other users' opinions/questions on that market**

# Acceptance Criteria
 *  Acceptance Criteria 1:  on the markets page, there is a section on each market showing the number of comments (to be created in #80 ) 
 *  Acceptance Criteria 2: clicking on this brings the user to a market details page where they can then see all the comments displayed

# Tasks
 - [x] Create market_details.html
 - [x] Add CSS as required
 - [x] Create the url for the view
 - [x] Create the market_details view
 - [x] link to the url from markets.html and my_markets.html
 - [x] Test manually
 - [x] Test the view

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual and automated testing completed. Closed.
