### ISSUE TITLE
USER STORY: Delete a comment

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#85]
As a **registered user** I can **delete a comment that I posted on a market** so that **I can remove it if I don't want others to see the comment or I posted it in error**

# Acceptance Criteria
 *  Acceptance Criteria 1:  When a user is logged in and viewing the comments on a market, any comment that the user posted has a link to delete it
 *  Acceptance Criteria 2: After clicking on the link they see a modal asking them to confirm deletion
 *  Acceptance Criteria 3: After confirming the deletion, the comment is no longer displayed on the page and there is a success message confirming the comment was deleted
 * Acceptance Criteria 4: The user cannot delete a comment that was added by someone else

# Tasks
 - [x] Add the delete link to the comments on market_details.html when the comment author is the logged in user
 - [x] Create the delete modal
 - [x] Add CSS as needed
 - [x] Create the view and url
 - [x] Test manually
 - [x] Test the view

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual and automated testing done. Closed.
