### ISSUE TITLE
ISSUE: Tidy up CSS class names for forms

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#87]
Originally class names were created for different forms however these were then used for later forms. The names need to be changed so they don't reference a specific form but are more general. The forms.py files will need to be changed as well as they add classes to the form fields.

# Tasks
 - [x] review the forms to see which ones are using the specific class names
 - [x] rename the class in the relevant CSS files to a generic name (and move to base.css for any that were in a specific css file)
 - [x] update each forms.py to add the new generic class instead of the specific one
 - [x] update each test_forms.py with the new test name for tests that check the class was added
 - [x] test manually

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. order-form and profile-form classes combined into brand-form, updated all .html templates that used either one of these classes to use the new class. Also order-form-input renamed to brand-form-input, this is added in each form init method, updated these and the test_forms.py also. Re-ran automated tests and tested manually. Closed.
