### ISSUE TITLE
USER STORY: See number of saves for a market

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#88]
As a **website owner** I can **see how many users have saved a market** so that **I can get an idea of how popular it might be**

# Acceptance Criteria
 *  Acceptance Criteria 1:  When a superuser is logged in, on the markets page each market card shows the number of saves for that market
 *  Acceptance Criteria 2:  When a superuser is logged in, on the market_details page the market details includes the number of saves for that market
 *  Acceptance Criteria 2: This information is not visible to regular users

# Tasks
 - [x] Update the view to return the saves for the markets (i.e. if they are on the saved market lists created by users)
 - [x] Update markets.html to display the information
 - [x] Update market_details view and template to show the number of saves
 - [x] Test the functionality

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Manual testing completed. Closed.
