### ISSUE TITLE
USER STORY: View products by category

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/knot-art#9]
As a **site user** I can **select a specific category of product** so that **I can view just the items in that category to make it easier to make a decision**

# Acceptance Criteria
 *  Acceptance Criteria 1: in the shop page menu bar, there are menu options to choose a particular category
 *  Acceptance Criteria 2: when a particular category is chosen, only the products in that category are displayed
 *  Acceptance Criteria 3: the options are the categories currently set up by the store owner: Living Room, Bedroom, Minis. There should also be an ALL category (which the shop page defaults to, but will be needed for the user if they want to go back to seeing all products after selecting a category)

# Tasks
 - [x] Menu for shop page should be created in #11. Add category options to menu
 - [x] Update show_products view to check if there is a request to filter by category, and to return the products in that category if there is
 - [x] Update the links in the products.html and product_details.html for the categories
 - [x] Test the functionality

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Also updated products nav to show current selected category. Manual and automated tests completed. Closed.
